version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
     -npm install
  build:
    commands:
      -npm run-script build
  post_build:
    commands:
     -aws s3 cp build s3://fbs-dev-app --recursive --acl public-read