phases:
  install:
    build:
      commands: '-npm run-script build'
    commands: '-npm install'
    post_build:
      commands: '-aws s3 cp build s3://fbs-dev-app --recursive --acl public-read'
    runtime-version:
      nodejs: 12
version: 0.2